import 'package:hive/hive.dart';

part 'recipe.g.dart'; // This part file is generated by Hive when you run the build_runner command

@HiveType(typeId: 0) // Type ID for this class (increment for other models)
class Recipe {
  @HiveField(0)
  final String title;

  @HiveField(1)
  final String? imageUrl; // Nullable field for image URL

  @HiveField(2)
  final List<String> ingredients;

  @HiveField(3)
  final String instructions;

  // Constructor for Recipe class
  Recipe({
    required this.title,
    this.imageUrl, // Nullable to handle cases with missing images
    required this.ingredients,
    required this.instructions,
  });

  // Factory method to create a Recipe instance from JSON
  factory Recipe.fromJson(Map<String, dynamic> json) {
    return Recipe(
      title: json['title'] ?? 'No Title', // Default to 'No Title' if null
      imageUrl: json['image'], // Allow null values
      ingredients: (json['extendedIngredients'] as List<dynamic>?)
          ?.map((ingredient) => ingredient['original'] ?? 'Unknown')
          .cast<String>()
          .toList() ??
          [], // Handle null or missing ingredients
      instructions: json['instructions'] ?? 'No instructions available',
    );
  }

  // Method to convert Recipe instance to JSON
  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'image': imageUrl,
      'extendedIngredients': ingredients
          .map((ingredient) => {'original': ingredient})
          .toList(),
      'instructions': instructions,
    };
  }
}
