// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzfTsYvu0JiZX2V37vtUsxsMJM60_-3e8',
    appId: '1:151959321901:web:32280a038ad105a0b727a4',
    messagingSenderId: '151959321901',
    projectId: 'recipe-generator-23318',
    authDomain: 'recipe-generator-23318.firebaseapp.com',
    storageBucket: 'recipe-generator-23318.firebasestorage.app',
    measurementId: 'G-P4HL3DRJ5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVGXT0re7aKBLRZae0s8rrv-s1yV9KycM',
    appId: '1:151959321901:android:c3a2cd41dcebf32ab727a4',
    messagingSenderId: '151959321901',
    projectId: 'recipe-generator-23318',
    storageBucket: 'recipe-generator-23318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP3MGaCSd3Avyc1L6mgmNNc10oiQCjczo',
    appId: '1:151959321901:ios:73c3070a2c7bf875b727a4',
    messagingSenderId: '151959321901',
    projectId: 'recipe-generator-23318',
    storageBucket: 'recipe-generator-23318.firebasestorage.app',
    iosBundleId: 'com.example.recipeGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP3MGaCSd3Avyc1L6mgmNNc10oiQCjczo',
    appId: '1:151959321901:ios:73c3070a2c7bf875b727a4',
    messagingSenderId: '151959321901',
    projectId: 'recipe-generator-23318',
    storageBucket: 'recipe-generator-23318.firebasestorage.app',
    iosBundleId: 'com.example.recipeGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzfTsYvu0JiZX2V37vtUsxsMJM60_-3e8',
    appId: '1:151959321901:web:1f069dcc6e03992ab727a4',
    messagingSenderId: '151959321901',
    projectId: 'recipe-generator-23318',
    authDomain: 'recipe-generator-23318.firebaseapp.com',
    storageBucket: 'recipe-generator-23318.firebasestorage.app',
    measurementId: 'G-GZ7Z8NCL81',
  );
}
